// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';
import { capacitorStorage } from '@/lib/capacitorStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Senza env vars createClient lancia ed esplode l'intero bundle prima
// che React possa montare → schermo bianco. Logghiamo e usiamo fallback
// così almeno l'app monta e l'utente vede l'errore nella console.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.includes("PLACEHOLDER")) {
  // eslint-disable-next-line no-console
  console.error(
    "[Pasify] Supabase env vars mancanti o placeholder. Aggiungi VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY a .env.local (vedi .env.example). Login e chiamate API non funzioneranno finché non sono settate."
  );
}

const SAFE_URL = SUPABASE_URL || "https://placeholder.supabase.co";
const SAFE_KEY = SUPABASE_PUBLISHABLE_KEY || "placeholder-anon-key";

// detectSessionInUrl solo su web: su Capacitor native il deep link è gestito
// dal listener appUrlOpen in App.tsx (per OAuth usiamo il plugin GoogleAuth).
const isNative = Capacitor.isNativePlatform();

export const supabase = createClient<Database>(SAFE_URL, SAFE_KEY, {
  auth: {
    storage: capacitorStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !isNative,
  }
});