// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';
import { capacitorStorage } from '@/lib/capacitorStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Senza env vars createClient lancia ed esplode l'intero bundle prima
// che React possa montare → schermo bianco. Logghiamo e usiamo fallback
// così almeno l'app monta e l'utente vede l'errore nella console.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.includes("PLACEHOLDER")) {
   
  console.error(
    "[Pasify] Supabase env vars mancanti o placeholder. Aggiungi VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY a .env.local (vedi .env.example). Login e chiamate API non funzioneranno finché non sono settate."
  );
}

const SAFE_URL = SUPABASE_URL || "https://placeholder.supabase.co";
const SAFE_KEY = SUPABASE_PUBLISHABLE_KEY || "placeholder-anon-key";

/**
 * Clave de la sesión en el storage. Es EXACTAMENTE la que supabase-js usa por
 * defecto (`sb-<primera etiqueta del host>-auth-token`, la misma cuenta que
 * hace createClient con la URL): cambiarla cerraría todas las sesiones
 * abiertas. Se fija aquí para que signOutLocal (useAuth.tsx) pueda borrar la
 * sesión de este dispositivo cuando auth-js no puede hacerlo (sin red).
 */
export const SUPABASE_AUTH_STORAGE_KEY = `sb-${new URL(SAFE_URL.trim()).hostname.split(".")[0]}-auth-token`;

// detectSessionInUrl solo su web: su Capacitor native il deep link è gestito
// dal listener appUrlOpen in App.tsx (per OAuth usiamo il plugin GoogleAuth).
const isNative = Capacitor.isNativePlatform();

export const supabase = createClient<Database>(SAFE_URL, SAFE_KEY, {
  auth: {
    storage: capacitorStorage,
    storageKey: SUPABASE_AUTH_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !isNative,
  }
});